<?php
namespace HolluxBundle\Repository;

/**
 * BoiteSmashUpRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoiteSmashUpRepository extends \Doctrine\ORM\EntityRepository
{
}
