<?php
namespace HolluxBundle\Repository;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * JeuxRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuxRepository extends \Doctrine\ORM\EntityRepository
{
	public function findJeuxQuestionByName($stringJeux)
	{
		$qb = $this->createQuerybuilder('j')->select('j')->Where('j.name = :stringJeux')
			->innerJoin('j.question', 'question')->addSelect('question')//Limite le QUESTION
		/* ->setMaxResults(1)*/
		->setParameters(['stringJeux' => $stringJeux]);

		return $qb->getQuery()->/*getResult*/
		getOneOrNullResult();
	}

	public function findJeuxAndAll($stringJeux, UserInterface $user)
	{
		$qb = $this->createQuerybuilder('j')//jeux
		->select('j')->where('j.name = :stringJeux')//questions
		->innerJoin('j.question', 'q')->addSelect('q')//response
		->leftJoin('q.response', 'r', 'WITH', 'r.user = :user')->addSelect('r')//tokenJeux
		->leftJoin('r.tokenJeux', 't', 'WITH', 't.jeux = j AND t.user = :user')->addSelect('t')//user
		->leftJoin('t.user', 'u')->addSelect('u')//Limite le QUESTION
		->setParameters(['stringJeux' => $stringJeux, 'user' => $user]);

		return $qb->getQuery()->/*getResult*/
		getOneOrNullResult();
	}

	// WTF ?!
	public function getQuestion($question, $token)
	{
		$qb = $this->createQuerybuilder('j')->select('j')->where('j.question = :question')->andWhere('j.name = :token')
			->setParameters(['question' => $question, 'token' => $token]);

		return $qb->getQuery()->getResult();
	}
}
