<?php

namespace HolluxBundle\Repository;

/**
 * MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Magasin2Repository extends \Doctrine\ORM\EntityRepository
{
}
