<?php

namespace HolluxBundle\Repository;

/**
 * Produit3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit3Repository extends \Doctrine\ORM\EntityRepository
{
}
