<?php

namespace HolluxBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit1Repository extends \Doctrine\ORM\EntityRepository
{
}
