<?php

namespace HolluxBundle\Repository;

/**
 * SmashUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmashUpRepository extends \Doctrine\ORM\EntityRepository
{
}
