<?php
namespace HolluxBundle\Repository;

use Symfony\Component\Security\Core\User\UserInterface;
use HolluxBundle\Entity\Jeux;

/**
 * TokenJeuxRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenJeuxRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByAuthorGame(UserInterface $user, Jeux $jeux)
	{
		$qb = $this->createQuerybuilder('t')->select('t')->leftJoin('t.user', 'user')->leftJoin('t.jeux', 'jeux')
			->addSelect('user')->addSelect('jeux')->where('t.user = :user')->andWhere('t.jeux = :jeux')
			->orderBy('t.id', 'DESC')->setMaxResults(1)->setParameters(['user' => $user, 'jeux' => $jeux]);

		return $qb->getQuery()->getOneOrNullResult();
	}
}
