<?php

namespace Admin\PortfolioBundle\Repository;

/**
 * TypePortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePortfolioRepository extends \Doctrine\ORM\EntityRepository
{
}
