<?php
namespace EcomBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\RouterInterface;
use HolluxBundle\Entity\Faction;

class LoadFaction extends AbstractFixture implements OrderedFixtureInterface
{

	public function load(ObjectManager $manager)
	{
		$faction1 = new Faction();
		$faction1->setName('Aliens');
		$faction1->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction1);
		$faction2 = new Faction();
		$faction2->setName('Zombies');
		$faction2->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction2);
		$faction3 = new Faction();
		$faction3->setName('Dinosaures');
		$faction3->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction3);
		$faction4 = new Faction();
		$faction4->setName('Pirates');
		$faction4->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction4);
		$faction5 = new Faction();
		$faction5->setName('Petit peuple');
		$faction5->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction5);
		$faction6 = new Faction();
		$faction6->setName('Sorciers');
		$faction6->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction6);
		$faction7 = new Faction();
		$faction7->setName('Ninja');
		$faction7->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction7);
		$faction8 = new Faction();
		$faction8->setName('Robots');
		$faction8->setBoiteSmashUp($this->getReference('boite1'));
		$manager->persist($faction8);
		$faction9 = new Faction();
		$faction9->setName('Fantomes');
		$faction9->setBoiteSmashUp($this->getReference('boite2'));
		$manager->persist($faction9);
		$faction10 = new Faction();
		$faction10->setName('SteamPunk');
		$faction10->setBoiteSmashUp($this->getReference('boite2'));
		$manager->persist($faction10);
		$faction11 = new Faction();
		$faction11->setName('Cavalerie Ours');
		$faction11->setBoiteSmashUp($this->getReference('boite2'));
		$manager->persist($faction11);
		$faction12 = new Faction();
		$faction12->setName('Plantes Carnivores');
		$faction12->setBoiteSmashUp($this->getReference('boite2'));
		$manager->persist($faction12);
		$faction13 = new Faction();
		$faction13->setName("Habitants d'innsmouth");
		$faction13->setBoiteSmashUp($this->getReference('boite3'));
		$manager->persist($faction13);
		$faction14 = new Faction();
		$faction14->setName('Université Miskatoni');
		$faction14->setBoiteSmashUp($this->getReference('boite3'));
		$manager->persist($faction14);
		$faction15 = new Faction();
		$faction15->setName('Grands Anciens');
		$faction15->setBoiteSmashUp($this->getReference('boite3'));
		$manager->persist($faction15);
		$faction16 = new Faction();
		$faction16->setName('Serviteurs du cthulhu');
		$faction16->setBoiteSmashUp($this->getReference('boite3'));
		$manager->persist($faction16);
		$faction17 = new Faction();
		$faction17->setName('Mutants');
		$faction17->setBoiteSmashUp($this->getReference('boite4'));
		$manager->persist($faction17);
		$faction18 = new Faction();
		$faction18->setName('Super Espions');
		$faction18->setBoiteSmashUp($this->getReference('boite4'));
		$manager->persist($faction18);
		$faction19 = new Faction();
		$faction19->setName('Singes cyborg');
		$faction19->setBoiteSmashUp($this->getReference('boite4'));
		$manager->persist($faction19);
		$faction20 = new Faction();
		$faction20->setName('Voyageurs du temps');
		$faction20->setBoiteSmashUp($this->getReference('boite4'));
		$manager->persist($faction20);
		$faction21 = new Faction();
		$faction21->setName('Loups garou');
		$faction21->setBoiteSmashUp($this->getReference('boite5'));
		$manager->persist($faction21);
		$faction22 = new Faction();
		$faction22->setName('Vampires');
		$faction22->setBoiteSmashUp($this->getReference('boite5'));
		$manager->persist($faction22);
		$faction23 = new Faction();
		$faction23->setName('Fourmis Géantes');
		$faction23->setBoiteSmashUp($this->getReference('boite5'));
		$manager->persist($faction23);
		$faction24 = new Faction();
		$faction24->setName('Savants fou');
		$faction24->setBoiteSmashUp($this->getReference('boite5'));
		$manager->persist($faction24);
		$faction25 = new Faction();
		$faction25->setName('Geek');
		$faction25->setBoiteSmashUp($this->getReference('boite6'));
		$manager->persist($faction25);
		$faction26 = new Faction();
		$faction26->setName('Kitty cat');
		$faction26->setBoiteSmashUp($this->getReference('boite7'));
		$manager->persist($faction26);
		$faction27 = new Faction();
		$faction27->setName('Chevaux mystiques');
		$faction27->setBoiteSmashUp($this->getReference('boite7'));
		$manager->persist($faction27);
		$faction28 = new Faction();
		$faction28->setName('Princesses');
		$faction28->setBoiteSmashUp($this->getReference('boite7'));
		$manager->persist($faction28);
		$faction29 = new Faction();
		$faction29->setName('Fées');
		$faction29->setBoiteSmashUp($this->getReference('boite7'));
		$manager->persist($faction29);
		$faction30 = new Faction();
		$faction30->setName('Magiciens');
		$faction30->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction30);
		$faction31 = new Faction();
		$faction31->setName('Voleurs');
		$faction31->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction31);
		$faction32 = new Faction();
		$faction32->setName('Guerriers');
		$faction32->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction32);
		$faction33 = new Faction();
		$faction33->setName('Orcs');
		$faction33->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction33);
		$faction34 = new Faction();
		$faction34->setName('Nains');
		$faction34->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction34);
		$faction35 = new Faction();
		$faction35->setName('Halfelin');
		$faction35->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction35);
		$faction36 = new Faction();
		$faction36->setName('Clercs');
		$faction36->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction36);
		$faction37 = new Faction();
		$faction37->setName('Elfs');
		$faction37->setBoiteSmashUp($this->getReference('boite8'));
		$manager->persist($faction37);
		$faction38 = new Faction();
		$faction38->setName('Tornades');
		$faction38->setBoiteSmashUp($this->getReference('boite9'));
		$manager->persist($faction38);
		$faction39 = new Faction();
		$faction39->setName('Dragons');
		$faction39->setBoiteSmashUp($this->getReference('boite9'));
		$manager->persist($faction39);
		$faction40 = new Faction();
		$faction40->setName('Grecs');
		$faction40->setBoiteSmashUp($this->getReference('boite9'));
		$manager->persist($faction40);
		$faction41 = new Faction();
		$faction41->setName('Hommes-Requins');
		$faction41->setBoiteSmashUp($this->getReference('boite9'));
		$manager->persist($faction41);
		$faction42 = new Faction();
		$faction42->setName('Super-héros');
		$faction42->setBoiteSmashUp($this->getReference('boite9'));
		$manager->persist($faction42);
		$faction43 = new Faction();
		$faction43->setName('Astroknights');
		$faction43->setBoiteSmashUp($this->getReference('boite10'));
		$manager->persist($faction43);
		$faction44 = new Faction();
		$faction44->setName('Changerbots');
		$faction44->setBoiteSmashUp($this->getReference('boite10'));
		$manager->persist($faction44);
		$faction45 = new Faction();
		$faction45->setName('Star Roamers');
		$faction45->setBoiteSmashUp($this->getReference('boite10'));
		$manager->persist($faction45);
		$faction46 = new Faction();
		$faction46->setName('Ignobles');
		$faction46->setBoiteSmashUp($this->getReference('boite10'));
		$manager->persist($faction46);
		$manager->flush();
	}

    public function getOrder()
    {
        return 3;
    }
}