<?php
namespace MediaBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data, $start = 0, $lenght = null)
    {
        $qb    = $this->createQueryBuilder('m');
        $query = isset($data['query']) && $data['query'] ? $data['query'] : null;
        if($query) {
            $qb->andWhere('m.filename like :query')->setParameter('query', "%".$query."%");
        }
        $qb->setFirstResult($start * $lenght)->setMaxResults($lenght);
        $list = new Paginator($qb);

        return $list;
    }
}
