<?php

namespace NewsBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function get20NewsVisibleBydate()
    {
        $qb =  $this->createQueryBuilder('n')
            ->where('n.isvisible = :val')
            ->orderBy('n.date', 'DESC')
            ->setMaxResults( 20 )
            ->setParameter('val', 1);

        return $qb->getQuery()->getResult();
    }

    public function getNewsForAdmin($first_result, $max_results = 20)
    {
        $qb = $this->createQueryBuilder('n')
            ->setFirstResult($first_result)
            ->setMaxResults($max_results)
            ->orderBy('n.id', 'DESC');

        $pag = new Paginator($qb);

        return $pag;
    }


}
