<?php

namespace Admin\NavBundle\Repository;

/**
 * NavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVisibleByOrder()
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.isvisible = :visible')
            ->orderBy('n.ordre')
            ->setParameters(['visible' => 1]);

        return $qb->getQuery()->getResult();

    }

    public function findByOrder()
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->orderBy('n.ordre')
        ;

        return $qb->getQuery()->getResult();
    }
}
