<?php

namespace ListBuilderBundle\Repository;

/**
 * ListTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
