<?php

namespace ListBuilderBundle\Repository;

/**
 * OptionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
