<?php
namespace VetBundle\Command\Handler;

use Symfony\Component\Config\Definition\Exception\Exception;

class VetCommandRepository implements VetCommandClassInterface
{
    public function addContent($content, $field, $fieldType, $lastLvl)
    {

    }

    public function liaison($content)
    {

    }

    public function end($content)
    {
        if(isset($content->data['category']))
        {
            $name = $content->data['category'];
        } else {
            $name = $content->data['analyse'];
        }
        $content->data['repository'] = $this->startContent($name).$content->data['repository'].$this->endContent($name);

    }

    public function startContent($name)
    {
        return "
<?php

namespace VetBundle\\Repository;

/**
 * ".ucfirst($name)."Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ".ucfirst($name)."Repository extends \\Doctrine\\ORM\\EntityRepository
{\r\n";
    }

    public function endContent($name)
    {

        return "}";
    }
}