<?php

namespace VetBundle\Repository;

/**
 * AntibiogrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntibiogrammeRepository extends \Doctrine\ORM\EntityRepository
{
}
