<?php

namespace VetBundle\Repository;

/**
 * AvortementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvortementRepository extends \Doctrine\ORM\EntityRepository
{
}