<?php

namespace VetBundle\Repository;

/**
 * BacteriologieLaitMammiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacteriologieLaitMammiteRepository extends \Doctrine\ORM\EntityRepository
{
}
