<?php

namespace VetBundle\Repository;

/**
 * BacteriologieAutresOrganesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacteriologieAutresOrganesRepository extends \Doctrine\ORM\EntityRepository
{
}
