<?php

namespace VetBundle\Repository;

/**
 * BacteriologieFecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacteriologieFecesRepository extends \Doctrine\ORM\EntityRepository
{
}
