<?php

namespace VetBundle\Repository;

/**
 * BacteriologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacteriologieRepository extends \Doctrine\ORM\EntityRepository
{
}