<?php

namespace VetBundle\Repository;

/**
 * BaseAvortementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseAvortementRepository extends \Doctrine\ORM\EntityRepository
{
}