<?php

namespace VetBundle\Repository;

/**
 * ComptageCellulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptageCellulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
