<?php

namespace VetBundle\Repository;

/**
 * EleveurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveurRepository extends \Doctrine\ORM\EntityRepository
{
}
