
<?php

namespace VetBundle\Repository;

/**
 * InformationscomplementairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationscomplementairesRepository extends \Doctrine\ORM\EntityRepository
{
}