<?php

namespace VetBundle\Repository;

/**
 * InhibiteursLaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InhibiteursLaitRepository extends \Doctrine\ORM\EntityRepository
{
}
