<?php

namespace VetBundle\Repository;

/**
 * MycologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MycologieRepository extends \Doctrine\ORM\EntityRepository
{
}