<?php

namespace VetBundle\Repository;

/**
 * navRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class navRepository extends \Doctrine\ORM\EntityRepository
{
}
