<?php

namespace VetBundle\Repository;

/**
 * ParasitologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParasitologieRepository extends \Doctrine\ORM\EntityRepository
{
}
