<?php

namespace VetBundle\Repository;

/**
 * PCRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PCRRepository extends \Doctrine\ORM\EntityRepository
{
}