<?php

namespace VetBundle\Repository;

/**
 * SerologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerologieRepository extends \Doctrine\ORM\EntityRepository
{
}