<?php

namespace VetBundle\Repository;

/**
 * VirologieAutresOrganesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirologieAutresOrganesRepository extends \Doctrine\ORM\EntityRepository
{
}
